@url=http://localhost:8080/api


###

GET {{url}}/findById/1 HTTP/1.1

###

GET {{url}}/findByIds/1,2 HTTP/1.1

###

POST {{url}}/authenticate HTTP/1.1
Content-Type: application/json

{
    "username": "john@smith.com",
    "password": "P@ssw0rd!"
}

###

POST {{url}}/create_account HTTP/1.1
Content-Type: application/json

{
  "username": "bob@jones.com",
  "password": "P@ssw0rd!"
}

###

PUT {{url}}/removeAttendee/3/2 HTTP/1.1
